

DROP TABLE U_STUDENTS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_STUDENTS_NUMBER;

DROP TABLE U_DEPARTMENT CASCADE CONSTRAINTS; 
DROP SEQUENCE SEQ_UNI_DEPT_CODE;

DROP TABLE U_COURSES  CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_COURSE_NUMBER;

DROP TABLE U_SECTIONS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_SECTION_NUM;

DROP TABLE U_GRADE_REPORTS CASCADE CONSTRAINTS;
